In [1]:
print("HARI OM")

HARI OM

In [30]:
import pandas as pd 
import numpy as np
import string

In [3]:
df=pd.read_csv("raw_data/samples.csv")

/var/folders/w_/hg7x5zzx15sg3m0gk991124m0000gn/T/ipykernel_43543/3646132645.py:1: DtypeWarning: Columns (5,25,26,31,33,34,41,42,44,46,47,48,49,50,51,52,53,54,55,56,57,60,61,64,65,66,67,69,71,72,77,81,82,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("raw_data/samples.csv")

In [4]:
df

,Run,AvgSpotLen,Bases,BioProject,BioSample,Collection_Date,Experiment,Country,Continent,Instrument,...,Confirmed_Cysts,Confirmed_Fibroids,Endo_Location,Endo_Stage,Heavy_Menstrual_Bleeding,Irregular_Menstrual_Bleeding,Sperm_Concentration,Sperm_Motility,Fertility,Dominant_Hand
0,DRR396973,600.0,19625797.0,PRJDB13875,SAMD00518187,2020-08-05,DRX382752,Japan,Asia,Illumina MiSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DRR396974,600.0,18183021.0,PRJDB13875,SAMD00518188,2020-08-18,DRX382753,Japan,Asia,Illumina MiSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DRR396975,600.0,13995744.0,PRJDB13875,SAMD00518189,2020-09-01,DRX382754,Japan,Asia,Illumina MiSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DRR396976,600.0,11623891.0,PRJDB13875,SAMD00518190,2020-08-19,DRX382755,Japan,Asia,Illumina MiSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DRR396977,600.0,15805829.0,PRJDB13875,SAMD00518191,2020-08-21,DRX382756,Japan,Asia,Illumina MiSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53444,SRR6704409,500.0,29148500.0,PRJNA398089,SAMN08514058,NaN,SRX3678347,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53445,SRR6704410,500.0,5972000.0,PRJNA398089,SAMN08514137,NaN,SRX3678522,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53446,SRR6704411,500.0,1083500.0,PRJNA398089,SAMN08514136,NaN,SRX3678521,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53447,SRR6704412,500.0,15674500.0,PRJNA398089,SAMN08514059,NaN,SRX3678520,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53448,SRR6704413,500.0,2341500.0,PRJNA398089,SAMN08514129,NaN,SRX3678519,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
unique_phenotypes=set()
for i in df["Phenotype"]:
    if(type(i)==float):
        continue
    i=i.lower()
    sep=i.split(",")
    for j in sep:
        unique_phenotypes.add(j)

In [32]:
print(len(unique_phenotypes))

103

In [33]:
for i in unique_phenotypes:
    print(i)

paediatric-onset orofacial granulomatosis
alzheimer's disease (ad)
silicosis
human immunodeficiency virus (hiv)
checkpoint inhibitor pneumonitis (cip)
endometrial cancer (ec)
crohn’s disease (cd)
mixed dentition
respiratory syncytial virus bronchiolitis (rsv)
diabetes
alcohol use disorder (aud)
breast cancer
melasma
colitis-associated carcinoma (cac)
epilepsy
recurrent urinary tract infection
vagal paraganglioma
endometrial hyperplasia
prostatitis
kidney transplant (recipient)
cirrhotic
graft-versus-host disease
atopic dermatitis
multiple sclerosis
non-small cell lung cancer (nsclc)
tongue squamous cell carcinoma (tscc)
small intestinal bacterial overgrowth (sibo)
kidney disease
barrett's
heart failure (hf)
intraductal papillary mucinous neoplasm (ipmn)
type ii diabetes (t2d)
abnormal sperm parameters
prostate cancer
pneumocystis pneumonia (pcp
cystic fibrosis (cf)
gastritis
healthy
schizophrenia (sz)
apical periodontitis
hbv-associated cirrhosis
obesity
gastric metaplasia
systemic sclerosis (ssc)
cervical cancer
ulcerative colitis (uc)
kidney transplant (donor)
pelvic organ prolapse
lung adenocarcinoma
guillain-barre syndrome
idiopathic pulmonary fibrosis (ipf)
pregnant
atopic dermatitis (ad)
craniofacial microsomia (cfm)
head and neck cancer
rheumatoid arthritis
chronic obstructive pulmonary disease (copd)
carotid paraganglioma
type i diabetes
critically ill
migraine
oral squamous cell carcinoma (oscc)
gestatiol diabetes
liver disease
autoimmune
posttraumatic stress disorder (ptsd)
autism spectrum disorder (asd)
community-acquired pneumonia
endometriosis (endo)
negative control
visual impairment
esophageal cancer
infective endocarditis
lung disease
gastric adenocarcinoma
attention deficit/hyperactivity disorder (adhd)
unknown
clostridioides difficile infection (cdi)
oropharyngeal squamous cell carcinoma (oscc)
colorectal cancer (crc)
chronic lymphocytic leukemia (cll)
post-covid-19 recovery
condyloma acuminatum (ca)
hepatocellular carcinoma (hcc)
microcolitis
chronic pelvic pain (cpp)
cardiovascular disease
chronic kidney disease (ckd)
acute exacerbation of chronic obstructive pulmonary disease (aecopd)
neonatal respiratory distress syndrome (nrds)
 jirovecii-infected)
irritable bowel syndrome (ibs)
extrahepatic cholangiocarcinoma
seasonal allergies
inflammatory bowel disease (ibd)
hypopharynx squamous cell carcinoma (hscc)
acute lymphoblastic leukemia (all)
congenital heart disease (chd)
type i diabetes (t1d)
covid-19 infection
acid reflux
metabolic syndrome (ms)
brain cancer

In [59]:
yes_time_series=0
no_time_series=0
empty=0
daf=pd.DataFrame()

for i in range(len(df["Time_series"])):
    if(df["Time_series"][i].lower()=="yes"):
        yes_time_series+=1
        daf = pd.concat([daf, df.iloc[[i]]], ignore_index=True)
    elif(df["Time_series"][i].lower()=="no"):
        no_time_series+=1
    else:
        empty+=1

In [61]:
print(yes_time_series)
print(no_time_series)
print(empty)

3375
50074
0

In [65]:
daf.tail()

,Run,AvgSpotLen,Bases,BioProject,BioSample,Collection_Date,Experiment,Country,Continent,Instrument,...,Confirmed_Cysts,Confirmed_Fibroids,Endo_Location,Endo_Stage,Heavy_Menstrual_Bleeding,Irregular_Menstrual_Bleeding,Sperm_Concentration,Sperm_Motility,Fertility,Dominant_Hand
3370,SRR6704409,500.0,29148500.0,PRJNA398089,SAMN08514058,NaN,SRX3678347,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3371,SRR6704410,500.0,5972000.0,PRJNA398089,SAMN08514137,NaN,SRX3678522,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3372,SRR6704411,500.0,1083500.0,PRJNA398089,SAMN08514136,NaN,SRX3678521,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3373,SRR6704412,500.0,15674500.0,PRJNA398089,SAMN08514059,NaN,SRX3678520,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3374,SRR6704413,500.0,2341500.0,PRJNA398089,SAMN08514129,NaN,SRX3678519,America (U.S.),North America,Illumina MiniSeq,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
daf.to_csv("time_series_data.csv")

In [86]:
arr=["P1","P2","P3","P4","P5"]

In [91]:
samples_5_time_series = pd.DataFrame()
for i in (1,31,1):
    rows = daf[daf["Participant_Id"] == str(i)]
    samples_5_time_series = pd.concat([samples_5_time_series, rows], ignore_index=True)

In [92]:
samples_5_time_series.to_csv("sample_5_time_series.csv")